title: J.D. Bean
description: > # this means to ignore newlines until "baseurl:"
  The blog of J.D. Bean: Full-stack developer. Former lawyer for Open Source. Current nerd.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jdbean.net" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: J.D. Bean # add your name
author-img: avatar.jpg # add your photo
about-author: >
    Lawyer turned full-stack developer. All around nerd
    with a hunger for learning. Passionate about open source,
    distributed systems, and security. Please enjoy my <a href="/projects"
    title="Portfolio">portfolio</a>&nbsp;&amp;&nbsp;<a href="/" title="Portfolio">blog</a>.

    <br/><br/><em>Actively seeking opportunites.</em>
social-twitter: bean_jd
# social-facebook: # add your Facebook handle
social-github: jdbean # add your GitHub handle
social-gitlab: jdbean # add your GitLab handle
social-linkedin: bean-jonathan
social-email: jdbean@jdbean.net
social-resume: "/resume.pdf"
portfolio-page: "/projects/"

# Disqus
# discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: UA-123652140-1

# Build Settings
markdown: kramdown
excerpt_separator: "<!-- more -->"
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

# Kramdown Settings
kramdown:
  header_offset: 1

paginate: 8
paginate_path: "/page/:num"

# PWA Settings
pwa:
  # sw_src_filepath: service-worker.js # Optional
  sw_dest_filename: service-worker.js # Optional
  dest_js_directory: assets/js # Required
  precache_recent_posts_num: 8 # Optional
  precache_glob_directory: / # Optional
  precache_glob_patterns: # Optional
    - "/assets/{js,css}/**/*.{js,css}"
    - "index.html"
    - "/projects/index.html"
    - "resume.pdf"
    - "/assets/img/avatar.jpg"
    - "/assets/img/portfolio/*"
    - "/assets/img/favicon/*"
  precache_glob_ignores: # Optional
    - sw-register.js

exclude:
  - "node_modules"
  - "gulpfile.js"
  - "package.json"
  - "yarn.lock"
  - "vendor"
  - "script"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE"
  - "package-lock.json"
  - "config.ru"
  - ".vscode"
