backend:
  name: gitlab
  repo: jdbean/professional-blog # Path to your GitLab repository
  auth_type: implicit # Required for implicit grant
  app_id: 5023deacb96574f88f7de84c1ffe99e089282d5584b0d8d6245171af095358ee # Application ID from your GitLab settings
  api_root: https://pracman.duckdns.org/api/v4
  base_url: https://pracman.duckdns.org
  auth_endpoint: oauth/authorize
  branch: develop
# This line should *not* be indented
media_folder: "assets/img" # Media files will be stored in the repo under images/uploads
collections:
  - name: "posts" # Used in routes, e.g. /admin/collections/blog
    label: "Posts" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "date"}
      - {label: "Featured Image", name: "img", widget: "image"}
      - {label: "Image Caption", name: "fig-caption", widget: "string", required: false}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}